### ISSUE TITLE
different behavior in windows for odo when KUBECONFIG is not set

### ISSUE THREAD

**Issue by girishramnani** [openshift/odo#1664]
[kind/bug]

## What versions of software are you using?
- Operating System: Windows 10
- Output of `odo version`: odo v1-beta

## How did you run odo exactly?
`odo login` 

## Actual behavior
` X not authorized`

## Expected behavior
` Server URL [http://localhost:8443]: ` interactive mode should be triggered

## Any logs, error output, etc?
One of the way to resolve this error is to set `KUBECONFIG` to ` ` using ENV variable GUI window in windows

**Comment by jorgemoralespou** [comment]
This also happens on Linux, but on linux it hangs, as it's probably "eating" the message due to other login related issues.
cc/ @kadel

**Comment by kadel** [comment]
"eating"  the message should be fixed in https://github.com/openshift/odo/pull/1652
@cdrage can you check if your PR is also going to resolve this issue?

**Comment by cdrage** [comment]
Yeah, looks like a separate bug:

```sh
admin@DESKTOP-A3JTM25 C:\Users\admin>odo.exe login                                                                              
Connecting to the OpenShift cluster                                                                                             


 X  not authorized                                                                                                                              

admin@DESKTOP-A3JTM25 C:\Users\admin>oc.exe login                                                                               
Login failed (401 Unauthorized)                                                                                                 
Verify you have provided correct credentials.                                                                                   
You must obtain an API token by visiting https://api.engint.openshift.com/oauth/token/request       
```

My PR does not fix the issue on Windows, it is however the same on Linux:


```sh
github.com/openshift/odo  add-show-log-to-watch ✔                                                                                                                                                                                                           4d
▶ odo login
 ✗  not authorized
```

I'll investigate this!

**Comment by cdrage** [comment]
I have gone ahead and fixed this in PR #1652 

```sh
make bin && ./odo login
go build -ldflags="-w -X github.com/openshift/odo/pkg/odo/cli/version.GITCOMMIT=2044e562" cmd/odo/odo.go
Connecting to the OpenShift cluster

Login failed (401 Unauthorized)
Verify you have provided correct credentials.
You must obtain an API token by visiting https://api.engint.openshift.com/oauth/token/request

 ✗  not authorized
```

This was fixed by adding information from `oc`: https://github.com/openshift/origin/blob/master/pkg/oc/cli/login/login.go#L60

**Comment by cdrage** [comment]
Hey @girishramnani did #1652 fix your issue? I can no longer replicate this.

**Comment by girishramnani** [comment]
sure, closing this issue
