### ISSUE TITLE
push triggers 4 deployments for git components

### ISSUE THREAD

**Issue by mik-dass** [openshift/odo#1682]
[kind/bug]

`odo push` triggers 4 deployments and 2 builds for git components

## Actual behavior
4 deployments and 2 builds

## Expected behavior
1 deployment and 1 build should be triggered

## Any logs, error output, etc?

```
[mrinaldas@localhost /]$ oc get dc
NAME              REVISION   DESIRED   CURRENT   TRIGGERED BY
nodejs-dnuu-app   2          1         1         config,image(nodejs-dnuu-app:latest)
[mrinaldas@localhost /]$ oc get dc
NAME              REVISION   DESIRED   CURRENT   TRIGGERED BY
nodejs-dnuu-app   6          1         1         config,image(nodejs-dnuu-app:latest)
```

**Comment by amitkrout** [comment]
@mik-dass i am closing thsi issue as it has been addressed in pr #1684.

**Comment by mik-dass** [comment]
https://github.com/openshift/odo/pull/1684 doesn't resolve this issue

/reopen
