### ISSUE TITLE
Install odo completion fails on MacOS using bash

### ISSUE THREAD

**Issue by GrooveCS** [openshift/odo#2474]
/kind bug

## What versions of the software are you using?

**Operating System:** 
- System Info
  - System Version:	macOS 10.14.6 (18G2022)
  - Kernel Version:	Darwin 18.7.0
- Hardware
  - Mac model id: MacBookPro15,1
  - Memory: 32 GB
  - Hard drive capacity: 500 GB
  - Hard drive used: 102 GB

**Output of `odo version`:**
- OpenShift version: 4.2.8 (embedded in binary)
- crc version: 1.2.0+c2e3c0f
- oc Client Version: v4.4.0 / Kubernetes Version: v1.14.6+dea7fb9
- odo v1.0.2 (HEAD)

## How did you run odo exactly? 

1. Open Bash Terminal
1. crc start -p pull-secret.txt
1. eval $(crc oc-env)
1. oc login -u ... -p ... <url>
1. odo --complete

## Actual behavior
The following error message: 

> $ odo --complete
> Install completion for odo? y
> Installing...
> Install failed! Did not find any shells to install

## Expected behavior

> $ odo --complete
> Install completion for odo? y
> Installing...
> Done!

## Any logs, error output, etc?
n/a

**Comment by hanvitha** [comment]
I have MacOS 10.14.6 (18G1012)
Install odo completed successfully
>odo --complete
Install completion for odo? y
Installing...
Done!

**Comment by GrooveCS** [comment]
@hanvitha,

I understand that it is working for you, yet it still not working for me. I removed ~/.crc and going to download the new CRC 4.2.10 and see if that works for me. 

> I have MacOS 10.14.6 (18G1012)
> Install odo completed successfully
> 
> > odo --complete
> > Install completion for odo? y
> > Installing...
> > Done!

**Comment by kadel** [comment]
> I understand that it is working for you, yet it still not working for me. I removed ~/.crc and going to download the new CRC 4.2.10 and see if that works for me.

It shouldn't be related to CRC.

The "Install failed! Did not find any shells to install"  error is coming from https://github.com/posener/complete/blob/05b68ffc813dd10c420993cb1cf927b346c057b8/cmd/install/install.go#L24 inside `github.com/posener/complete`  library that we use for handling and generating autocompletion for shells. 

@GrooveCS What shell do you use? You can run the following command to get name of the currently used shell.
```
echo $0
```

**Comment by GrooveCS** [comment]
Hi @kadel,

> What shell do you use? 

```
MacBook-Pro:~ parrislucas$ echo $0
-bash
MacBook-Pro:~ parrislucas$ echo $SHELL
/usr/local/bin/bash
```
The macOS comes with a default bash, yet using brew I updated to the current version. Using the following script.

```
MacBook-Pro:~ parrislucas$ brew ls bash 
/usr/local/Cellar/bash/5.0.11/bin/bash
/usr/local/Cellar/bash/5.0.11/bin/bashbug
/usr/local/Cellar/bash/5.0.11/include/bash/ (58 files)
/usr/local/Cellar/bash/5.0.11/lib/bash/ (29 files)
/usr/local/Cellar/bash/5.0.11/lib/pkgconfig/bash.pc
/usr/local/Cellar/bash/5.0.11/share/doc/ (10 files)
/usr/local/Cellar/bash/5.0.11/share/info/bash.info
/usr/local/Cellar/bash/5.0.11/share/locale/ (38 files)
/usr/local/Cellar/bash/5.0.11/share/man/ (2 files)
```

I will check now, and provide feedback shortly. I just updated last night to latest 4.3.

**Comment by GrooveCS** [comment]
@kadel I'm getting the expected behavior with 

```bash
#!/bin/bash
odo v1.0.3 (HEAD)
Server: https://api.crc.testing:6443
Kubernetes: v1.14.6+a8d983c
crc version: 1.4.0+d5bb3a3
OpenShift version: 4.2.13 
```
Thank you for your assistance

**Comment by girishramnani** [comment]
closing this issue as it seems to be resolved, if it isn't then please feel free to reopen it.
