### ISSUE TITLE
Pods are terminated and new pods started on initial odo link and every subsequent odo push

### ISSUE THREAD

**Issue by ajm01** [openshift/odo#3803]
/kind bug

## What versions of software are you using?

**Operating System:**
Red Hat Enterprise Linux Server 7.6 (Maipo)
Kernel: Linux 3.10.0-1062.12.1.el7.x86_64

**Output of `odo version`:**
[root@slobbed-inf jpa]# odo version
odo v1.2.5 (8b6a698)

Server: https://api.slobbed.os.fyre.ibm.com:6443
Kubernetes: v1.16.2

## How did you run odo exactly?
odo link ServiceBindingRequest/example-servicebindingrequest

## Actual behavior
link is established, pod is terminated and new pod started
every subsequent `odo push` results in the current pod being terminated and a new pod initialized

## Expected behavior
link is established, pod is terminated and new pod started
every subsequent `odo push` should not cause the current pod to be terminated - current pod should be maintained

## Any logs, error output, etc?
I have the output of requesting the pod yaml at each step - pre-link, post-link, post-link-push, post-link-app-
[podyamls.zip](https://github.com/openshift/odo/files/5105684/podyamls.zip)
update-push

**Comment by dharmit** [comment]
We're making a bunch of changes (#4159, #4160 and #4242) under the hood of `odo service` and `odo link` as far as Operator Hub integration is concerned. I'm marking this as a low priority as a result.

/priority low
/remove-lifecycle stale

**Comment by scottkurz** [comment]
On odo v2.0.4, I'm still seeing this.   That is, I do:

1. odo push # initial
2. odo link  #  To a service created via this operator: https://operatorhub.io/operator/postgresql-operator-dev4devs-com
3. odo push # Expect a new pod here
4. Make trivial source change
5. odo push #  I see a whole new pod, which I shouldn't

I can gather some more logs if it helps, but since @dharmit had said this was a low priority during refactoring I'll wait for him to ask first.  Thanks.

**Comment by dharmit** [comment]
>  5\. odo push _#  I see a whole new pod, which I shouldn't_

This is a problem on odo side but, tbh, I have not dug into this because...

> I can gather some more logs if it helps, but since @dharmit had said this was a low priority during refactoring I'll wait for him to ask first. Thanks.

We're working on changing the experience with `odo link` (#4208) and other service commands like `odo service create`, `odo service delete` (#4159 & #4160). I expect this bug to get addressed along with #4208.

/remove-priority low
/priority medium

**Comment by valaparthvi** [comment]
Perhaps this will not be a problem with the new changes to odo link. odo link no longer pushes any change to the server, it only does on odo push.
@feloy?

**Comment by feloy** [comment]
> Perhaps this will not be a problem with the new changes to odo link. odo link no longer pushes any change to the server, it only does on odo push.
> @feloy?


I think that this issue is fixed by #4819:

1. create a component and a service
2. odo push
3. odo link *service*
4. oso push # the component is restarted, as expected
5. odo push # the component is not restarted
6. edit sources files
7. odo push # the component is not restarted, and files are synced on the running component

**Comment by dharmit** [comment]
Closing this issue.

@ajm01 @scottkurz if you folks are still facing problems, feel free to reopen it.

/close

**Comment by scottkurz** [comment]
@dharmit @feloy - Still seeing this issue with v2.2.3 following the update-pending doc here:  https://github.com/openshift/odo/blob/9188588b66e16984da8122001794f009a6a09235/docs/public/deploying-java-app-with-database.adoc)

Can we please reopen this?  I'll try to add some logs.
