### ISSUE TITLE
nodejs (devfile) and nodejs/12 (s2i) components are not accessible after push, but java-quarkus (devfile) works fine

### ISSUE THREAD

**Issue by dgolovin** [openshift/odo#4245]
/kind bug

## What versions of software are you using?

**Operating System:** Linux

**Output of `odo version`:** 2.0.1

## How did you run odo exactly?

Local single node OpenShift cluster

```
./crc status
CRC VM:          Running
OpenShift:       Running (v4.6.1)
Disk Usage:      21.31GB of 32.72GB (Inside the CRC VM)
Cache Usage:     41.01GB
Cache Directory: /home/denis/.crc/cache
```

```
"/home/denis/p/vscode-openshift-tools/out/tools/linux/odo" create nodejs n4  --context /home/denis/p/review-workspace/nodejs-devfile4 --app app1 --project sprint-review --starter
Devfile path: 
Validation
 •  Checking devfile existence  ...

 ✓  Checking devfile existence [15062ns]
 •  Creating a devfile component from registry: DefaultDevfileRegistry  ...

 ✓  Creating a devfile component from registry: DefaultDevfileRegistry [13128ns]
 •  Validating devfile component  ...

 ✓  Validating devfile component [68157ns]

Starter Project
 •  Downloading starter project nodejs-starter from https://github.com/odo-devfiles/nodejs-ex.git  ...

 ✓  Downloading starter project nodejs-starter from https://github.com/odo-devfiles/nodejs-ex.git [785ms]

Please use `odo push` command to create the component with source deployed
```

```
$ "/home/denis/p/vscode-openshift-tools/out/tools/linux/odo" push --debug

Validation
 ✓  Validating the devfile [45874ns]

Creating Kubernetes resources for component n4
 ✓  Waiting for component to start [6s]

Applying URL changes
 ✓  URL http-3000: http://http-3000-n4-sprint-review.apps-crc.testing/ created

Syncing to component n4
 ✓  Checking files for pushing [695353ns]
 ✓  Syncing files to the component [753ms]

Executing devfile commands for component n4
 ✓  Executing install command "npm install" [3s]
 ✓  Executing debug command "npm run debug" [1s]

Pushing devfile component n4
 ✓  Changes successfully pushed to component
```

```
$ "/home/denis/p/vscode-openshift-tools/out/tools/linux/odo" log
time="2020-11-20T07:37:19Z" level=info msg="create process:devrun" 
time="2020-11-20T07:37:19Z" level=info msg="create process:debugrun" 
time="2020-11-20T07:37:24Z" level=debug msg="no auth required" 
time="2020-11-20T07:37:24Z" level=debug msg="succeed to find process:debugrun" 
time="2020-11-20T07:37:24Z" level=info msg="try to start program" program=debugrun 
time="2020-11-20T07:37:24Z" level=info msg="success to start program" program=debugrun 
ODO_COMMAND_DEBUG is npm run debug
Changing directory to /project
Executing command cd /project && npm run debug

> nodejs-starter@1.0.0 debug /project
> node --inspect-brk=${DEBUG_PORT} server.js

Debugger listening on ws://127.0.0.1:5858/fad0a98a-3347-43a1-a91c-223b858a1ec5
For help, see: https://nodejs.org/en/docs/inspector
time="2020-11-20T07:37:25Z" level=debug msg="wait program exit" program=debugrun
```
## Actual behavior

Cannot reach the app in browser
![image](https://user-images.githubusercontent.com/620330/99773679-a75ee180-2ac1-11eb-9942-77dd51f3aa74.png)

## Expected behavior

Should be reachable

**Comment by kadel** [comment]
verified, hitting the same problem
/priority high

**Comment by kadel** [comment]
fixed.
Problem was that the example (starter project) was using `--inspect-brk` for debugging. This makes the user code break before startup (to allow debugging startup sequence). This should not be a default option. 

/close

**Comment by dgolovin** [comment]
@kadel nodejs/12 s2i is deployed fine, but nodejs devfile component is still not accessible after creating it using starter project and pushing it to the cluster.
